title: "Learn Writing Python Like an Engineer"
description: ""
url: "https://eliza-guseva.github.io"
baseurl: "/prod-ai-eng-python-moodtracker"
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: auto

